spring:
  mail:
    host: smtp.163.com
    username: m6162390748@163.com
    password: m6162390748
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: true
  thymeleaf:
    cache: false
    enabled: false
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      buffered: true
      directory: /tmp/log
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
    max-connections: 2000
    max-threads: 100
  port: 80