spring:
  mail:
    host: smtp.163.com
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8